export const CHANGE_SINGER_LIST = 'CHANGE_SINGER_LIST' // 改变歌手列表
export const CHANGE_SINGER_ENTER_LOADING = 'CHANGE_SINGER_ENTER_LOADING' // loading
export const CHANGE_SINGER_PAGE_COUNT = 'CHANGE_SINGER_PAGE_COUNT' // 页码 
export const CHANGE_SINGER_PULLDOWN_LOADING = 'CHANGE_SINGER_PULLDOWN_LOADING' // 下拉loading
export const CHANGE_SINGER_PULLUP_STATUS = 'CHANGE_SINGER_PULLUP_STATUS' // 上拉状态
